<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Rivo.Domain\Rivo.Domain.csproj" />
    <ProjectReference Include="..\Rivo.Infrastructure\Rivo.Infrastructure.csproj" />
    <ProjectReference Include="..\Rivo.Shared\Rivo.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
